In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
import seaborn as sns

In [3]:
titanic = sns.load_dataset('titanic').dropna()

In [4]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1          1       1  female  38.0      1      0  71.2833        C  First   
3          1       1  female  35.0      1      0  53.1000        S  First   
6          0       1    male  54.0      0      0  51.8625        S  First   
10         1       3  female   4.0      1      1  16.7000        S  Third   
11         1       1  female  58.0      0      0  26.5500        S  First   

      who  adult_male deck  embark_town alive  alone  
1   woman       False    C    Cherbourg   yes  False  
3   woman       False    C  Southampton   yes  False  
6     man        True    E  Southampton    no   True  
10  child       False    G  Southampton   yes  False  
11  woman       False    C  Southampton   yes   True

In [5]:
from sklearn.linear_model import LogisticRegression

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = titanic[['pclass', 'age', 'sibsp', 'parch', 'fare', 'adult_male']]

In [8]:
y = titanic.survived

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [10]:
clf = LogisticRegression()

In [11]:
clf.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [12]:
clf.predict(X_test)

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1])

## FLASK

In [14]:
import spacy

ModuleNotFoundError: No module named 'spacy'

In [15]:
nlp = spacy.load('en')

NameError: name 'spacy' is not defined

In [16]:
sent1 = nlp("This record is smelly.")
sent2 = nlp("I am funky.")

NameError: name 'nlp' is not defined

In [17]:
sent1.similarity(sent2)

NameError: name 'sent1' is not defined

In [18]:
rev1 = nlp(pitch.text[0])

NameError: name 'nlp' is not defined

In [19]:
rev2 = nlp(pitch.text[1])

NameError: name 'nlp' is not defined

In [20]:
rev1.similarity(rev2)

NameError: name 'rev1' is not defined

In [21]:
pitch.head(2)

NameError: name 'pitch' is not defined

In [22]:
sim = []
for i in pitch.text:
    temp = nlp(i)
    sim.append(rev1.similarity(temp))

NameError: name 'pitch' is not defined

In [23]:
pitch['similarity'] = sim

NameError: name 'pitch' is not defined

In [24]:
pitch.nlargest(10, 'sim')

NameError: name 'pitch' is not defined

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
text = ["That movie really sucked.", "I wish there was more dancing."]

In [15]:
cvect = CountVectorizer()

In [16]:
cvect.fit(text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [17]:
print("The number of unique words is, {}".format(len(cvect.vocabulary_)))

The number of unique words is, 9


In [18]:
print("The unique words are, {}".format(cvect.vocabulary_))

The unique words are, {'that': 5, 'movie': 2, 'really': 3, 'sucked': 4, 'wish': 8, 'there': 6, 'was': 7, 'more': 1, 'dancing': 0}


In [19]:
bag = cvect.transform(text)
print("The representation of the bag of words would be: \n", bag.toarray())

The representation of the bag of words would be: 
 [[0 0 1 1 1 1 0 0 0]
 [1 1 0 0 0 0 1 1 1]]


In [20]:
pd.DataFrame(bag.toarray(), columns = cvect.get_feature_names())

dancing  more  movie  really  sucked  that  there  was  wish
0        0     0      1       1       1     1      0    0     0
1        1     1      0       0       0     0      1    1     1

In [ ]:
pitch = pd.read_json('cleaned_pitch.json')

In [ ]:
pitch.info()

In [ ]:
cvect = CountVectorizer(stop_words='english', max_features= 300)
wrds = cvect.fit_transform(pitch.text)

In [ ]:
wrds

In [ ]:
review_words = pd.DataFrame(wrds.toarray(), columns = cvect.get_feature_names())

In [ ]:
review_words.head()

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(review_words, pitch.score)

In [ ]:
lr.score(review_words, pitch.score)

In [ ]:
sample_reviews = pitch.iloc[:5]

In [ ]:
predictions = lr.predict(cvect.fit_transform(sample_reviews.text))

In [ ]:
for i in range(len(predictions)):
    print("The actual value for the review was ", sample_reviews.iloc[i, 3], "\n the prediction was ", predictions[i])

In [ ]:
pitch.head()

In [ ]:
pitch.info()

In [ ]:
from textblob import TextBlob

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
pitch.text[0]

In [ ]:
cvect = CountVectorizer()

In [ ]:
small_reviews = pitch.iloc[:5]

In [ ]:
cvect.fit_transform(small_reviews.text)

In [ ]:
cvect.

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('yelp.csv')

In [ ]:
df.info()